// <auto-generated />
namespace MyHomework.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class StudentDataChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudentDataChange));
        
        string IMigrationMetadata.Id
        {
            get { return "202110131820140_StudentDataChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
